### ISSUE TITLE
stuck at loading files - FIXED

### ISSUE THREAD

**Issue by xboxcopy** [spriteuv/SpriteUV2#1]
I have installed spriteUV2 on my main desktop and personal laptop. pro license.  works fine on desktop win7, but stuck on laptop win10 after click "build", constant at 0% loading files. I can load files picture or fbx into spriteUV, also can modify all the setting. all other programs runs fine.
any possible solution? thanks.

**Comment by spriteuv** [comment]
Can you see generated sprite mesh in SpriteUV veiewport ?

**Comment by xboxcopy** [comment]
I can see the loaded png preview as well as fbx mesh preview with its textures. but after i click build, it stays at loading files 0% 

    On Tuesday, February 28, 2017 3:11 AM, SpriteUV <notifications@github.com> wrote:
 

 Can you see generated sprite mesh in SpriteUV veiewport ?—

**Comment by spriteuv** [comment]
@xboxcopy if I understand correctly, the same PNG works fine on desktop, but not on the laptop with Win10? And if you use only FBX file then it works fine on both ?

**Comment by xboxcopy** [comment]
somehow after I restart the laptop couple of times it works 9 out of 10 times, also I tried the same file on desktop, and one time it stuck too. I will do some more detailed tests tomorrow, its 4am here.  thanks for the support. 

    On Tuesday, February 28, 2017 3:38 AM, SpriteUV <notifications@github.com> wrote:
 

 @xboxcopy if I understand correctly, the same PNG works fine on desktop, but not on the laptop with Win10? And if you use only FBX file then it works fine on both ?—

**Comment by xboxcopy** [comment]
so I figure out how to recreate the issue. whenever I try to import 4k textures, whether is sprites or assigned FBX textures, spriteUV2 will break, exported altas file and mesh location will alway invalid. if I import fbx files and 1k texture, all system will work fine, only when I assign a 4k texture to the fbx, things will not work, even if I reassign a 1k texture back, SUV2 remains break. restart, import fbx, assign 1k texture will work again.regardless of operation system.
in summary, import 4k img is NO NO.   

    On Tuesday, February 28, 2017 3:52 AM, ya <xboxcomcn@yahoo.com> wrote:
 

 somehow after I restart the laptop couple of times it works 9 out of 10 times, also I tried the same file on desktop, and one time it stuck too. I will do some more detailed tests tomorrow, its 4am here.  thanks for the support. 

    On Tuesday, February 28, 2017 3:38 AM, SpriteUV <notifications@github.com> wrote:
 

 @xboxcopy if I understand correctly, the same PNG works fine on desktop, but not on the laptop with Win10? And if you use only FBX file then it works fine on both ?—

**Comment by spriteuv** [comment]
@xboxcopy Thank you for the details. Can you tell me how many polygons are inside this FBX file ? Also when you assign 4k texture can you check in Task manager if SpriteUV Packer actually doing something or just dead? If it's busy then even when you reassign different texture it will check if something has changed in the document only when it finish with current item. And if it's possible could  you send me those files on spriteuv@gmail.com , so I could reproduce the issues and fix it? I've tried to use 4K with FBX and it worked well. Maybe there is something specific about those files.

**Comment by spriteuv** [comment]
@xboxcopy  Thank you for reporting this issue! i've fixed it in the new 1.14 release. Please check it  out.
