### ISSUE TITLE
JSON format description

### ISSUE THREAD

**Issue by loudoweb** [spriteuv/SpriteUV2#2]
Hello it's me again,

I have some trouble on using the json file and I thought that github is a better place than [reddit](https://www.reddit.com/r/gamedev/comments/5nj5v3/spriteuv2_a_texture_sprite_uv_map_packer_that_you/).

You said that **v2** values are related to mesh pivots. OK. But can you tell me more about the values itself? They are between -1 and 1 right? My first reflex would be to multiply it by width/height of the image/mesh. But the json file doesn't contain these values. So what should I do with these values?

Also, I don't understand the position of the pivot. In SpriteUV2 when I select for example **relative 0.5,0.5**, I don't retrieve it in the json (instead I have a mesh position  "x": 1.455,"y": 1.465..but relative to what?). Can you explain what values are you generating and how can I use it in my engine?

Thanks.

EDIT: for now I'm able to draw on screen mesh by mesh the atlas by calculating the vertices as following: 
mesh.vertices[i] = mesh.uv[i] * atlasSize; So all my meshes have the same position as in the atlas. But now I need to control the pivot and position of the mesh.

**Comment by spriteuv** [comment]
Hi! Sorry fro the late response

Yeah you’re totally right. I'll put JSON description from reddit here too.

Format is very simple. 
**pos** - mesh position in world coordinates;
**mesh** - property contains array of meshes. Inside "mesh" object:
- **tri** - triangle description (numbers are vertex indices, so 3 number in a row describes a single triangle );
- **uv** - uv coordinates of a vertex (2 numbers, first X second Y, 0.0 bottom left corner, 1.0 upper right corner);
- **v2** - vertex coordinates (2 numbers, first X second Y, relative to pivot);

UVs and Vertex position (v2) have different coordinates.

You don’t need to multiply **v2** positions to image size, those positions are for the game world, not for the image data, and it doesn’t have any limitation. To get image data, you need to use UVs, By multiplying atlas image width and height by **uv** value you will get triangle vertex position in image atlas coordinates. I think for better understanding what is going on in exported json file, you can set the following values and see what happens:
 Exported group -> Pixel Per Unit = 1;
 Sprite settings -> Mesh type = FRAME; Pivot = Absolute; x:0 y:0; 
 
Then you can play with those values to see how various settings affecting to exported json;

**Comment by loudoweb** [comment]
Ok thanks to point me to the **Pixel Per Unit** parameter. That was the source of my misunderstanding.
Now everything is working.
Any reason to set the default to 100?

**Comment by spriteuv** [comment]
I've set 100 as default simply because Unity has the same value, so I thought for Unity users it might be easier to get along with SpriteUV
